### ISSUE TITLE
Plugins development

### ISSUE THREAD

**Issue by interstar** [fedwiki/wiki-node#40]
I'm not sure if this is now the right repository to ask in, but is 

https://gist.github.com/WardCunningham/fced775fcedcee133b32

up-to-date / still relevant? 

I'm finding that when I create a new plugin with that script : sym-link from my wiki/node_modules directory and restart wiki, I don't see a page at /about-myplugin-plugin.html as the instructions  suggest. Nor does it seem to recognise plugins with that name.

(I'm just updating my version of SFW after about 18 months, so I need to update my plugin to the new standard.)

**Comment by WardCunningham** [comment]
Yes, this makes a good first draft of plugins.

I often double check that I'm putting the links in the right place. Here is what it looks like from my 

```
$ pwd
/Users/ward/FedWiki/wiki-node
$ ls -l node_modules/ | head
total 120
drwxr-xr-x@ 13 ward  staff  442 Oct 17 08:45 bouncy
drwxr-xr-x@ 14 ward  staff  476 Nov 15 17:07 coffee-script
drwxr-xr-x@  8 ward  staff  272 Oct 17 08:45 coffee-trace
drwxr-xr-x@  9 ward  staff  306 Jul  4  2014 config-chain
drwxr-xr-x   9 ward  staff  306 Feb  7 06:46 glob
drwxr-xr-x@ 10 ward  staff  340 Jul  4  2014 optimist
lrwxr-xr-x   1 ward  staff   39 Nov 24 07:06 wiki-client -> /usr/local/lib/node_modules/wiki-client
lrwxr-xr-x   1 ward  staff   48 Mar 15 09:20 wiki-plugin-activity -> /usr/local/lib/node_modules/wiki-plugin-activity
drwxr-xr-x   8 ward  staff  272 Feb  7 06:46 wiki-plugin-bars
```

This is my test server. I launch it with one command from the same directory.

```
$ node index.js
```

**Comment by interstar** [comment]
Thanks.

OK. I was trying to use nvm (node version manager) to make separate node installations. I've now just tried switching back to the offical Ubuntu node package, using a personal npm/node_modules directory in my home/phil directory and the sym-link now works. I guess I had the paths screwed up somehow.

Sorry to bother you with that. 

cheers

Phil

**Comment by WardCunningham** [comment]
If you find something that works reliability be sure to tell us about it.
