### ISSUE TITLE
Quick questions on plugin dev 

### ISSUE THREAD

**Issue by interstar** [fedwiki/wiki-node#41]
Here's the *expand* for my reworked plugin : 

    expand = (text)->
        mp = new MarkupProcessor('')
        text = mp.page(text)
        text = wiki.resolveLinks(text)

And here's *emit*

    emit = ($item, item) ->
      $item.append """
        <p style="background-color:#eee;padding:15px;">
        #{expand item.text}
        </p>
     """

Two questions. 

1) I get a failure trying to resolveLinks in the unit-tests because it says it can't find "wiki". Presumably it's not in scope in the tests. Though it seems to be when rendered by SFW itself.

This isn't fatal but is there a way to avoid it?

2) The HTML in the result is still being escaped into &lt;h3&gt; &amp;amp; etc. I'm not doing this in my MarkupProcessor, and I removed the lines that did it in the example expand. So where is it happening? And can I turn it off?

**Comment by interstar** [comment]
OK. I can take the resolveLinks out of expand and just wrap the return from emit with it. So I guess that resolves the first.

Still can't find where the html is escaped though.

**Comment by paul90** [comment]
It is being done within resolveLinks - there is a second argument that can be used to provide a substitute text sanitizer. See the html plugin for an example.

**Comment by interstar** [comment]
Hmmm ... the html example seems to use sanitize-caja. 

I npm installed that, but my plugin is now blowing up saying it can't find it. It seems to be in the wiki-server packages though. 

Is there a way of giving resolveLinks a dummy / null sanitizer that doesn't escape HTML?

**Comment by interstar** [comment]
Ah ... ok. Looking at the Markdown plugin I see you can actually use the expand AS the sanitizer.

That's slightly counter-intuitive. But it seems to work.

**Comment by interstar** [comment]
Thanks.
