### ISSUE TITLE
wiki-node or wiki-node-server?

### ISSUE THREAD

**Issue by ralphtheninja** [fedwiki/wiki-node#42]
Hi,

I'm wondering which one of these to use and the difference between them. It's a bit confusing that they have similar names and with equal activity :)

Any help is greatly appreciated!

**Comment by interstar** [comment]
Just to use, install the wiki package using npm

    npm install -g wiki

**Comment by ralphtheninja** [comment]
@interstar Thanks for reply. I'm interested in the code as well, so need to know the correct repo. So now I can do `npm info wiki` :)
