### ISSUE TITLE
Recently Cloned Page Misbehaves

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-node#44]
I can confirm a persistent problem my end (using latest FireFox on OSX). Forked pages are not recognised when drag and dropped onto factories to create reference links. Not all the time but frequently this is the case (I can't pin down why).

I do know the fix however. If the forked page refuses to allow itself to be dropped onto a factory - you can encourage her by refreshing the web page (command R) - then it will work.

This odd behaviour with regard to recently cloned pages is also true when you drag and drop it onto a new tab. Instead of opening a new panel, it replaces the entire url. Again refreshing the web page that contains the recently cloned page restores the normal behaviour.

**Comment by WardCunningham** [comment]
Thanks for tracking this down to a repeatable case.

**Comment by paul90** [comment]
This issue is fixed in wiki-client version 0.4.10
