### ISSUE TITLE
Trouble: Can't Get Page 

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-node#45]
When fetching the following page I get an error - http://wiki.parliamentofthings.org/view/map-of-science:

The page handler has run into problems with this request.
<pre class=error>{"slug":"map-of-science"}</pre>The requested url.<pre class=error>/map-of-science.json</pre> The server reported status. <pre class=error>500</pre>

From the console I get the following information and warnings:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead map-of-science:618:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-migrate-1.1.1.min.js:3:0
"Window Name: wiki.parliamentofthings.org" map-of-science:666:458
syntax error map-of-science.json:1:1
"pageHandler.get error" Object { readyState: 4, getResponseHeader: .ajax/N.getResponseHeader(), getAllResponseHeaders: .ajax/N.getAllResponseHeaders(), setRequestHeader: .ajax/N.setRequestHeader(), overrideMimeType: .ajax/N.overrideMimeType(), statusCode: .ajax/N.statusCode(), abort: .ajax/N.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 11 more… } 500 "error" "Internal Server Error" map-of-science:666:26625
".page keys " Array [ "154966d1" ] map-of-science:667:7521
"lineup keys" Array [ "154966d1" ] map-of-science:667:7660
"ajax error" Object { type: "ajaxError", timeStamp: 1428657373645, jQuery19106335917615261464: true, isTrigger: true, namespace: "", namespace_re: null, result: undefined, target: HTMLDocument → map-of-science, delegateTarget: HTMLDocument → map-of-science, currentTarget: HTMLDocument → map-of-science, 2 more… } Object { readyState: 4, getResponseHeader: .ajax/N.getResponseHeader(), getAllResponseHeaders: .ajax/N.getAllResponseHeaders(), setRequestHeader: .ajax/N.setRequestHeader(), overrideMimeType: .ajax/N.overrideMimeType(), statusCode: .ajax/N.statusCode(), abort: .ajax/N.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 11 more… } Object { url: "/map-of-science.json?random=9c116c9b", type: "GET", isLocal: false, global: true, processData: true, async: true, contentType: "application/x-www-form-urlencoded; charset=UTF-8", accepts: Object, contents: Object, responseFields: Object, 11 more… } map-of-science:666:13426
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. map-of-science:620:0
"textEditor" "900f81790a29ef8c" Object { append: true } map-of-science:666:5158
"textEditor" "900f81790a29ef8c" Object { append: true } map-of-science:666:5158

**Comment by WardCunningham** [comment]
You might try looking at your server log to see why it returned 500. 

On Apr 10, 2015 2:21 AM, David Bovill <notifications@github.com> wrote:When fetching the following page I get an error - http://wiki.parliamentofthings.org/view/map-of-science:

The page handler has run into problems with this request.

{"slug":"map-of-science"}The requested url./map-of-science.json The server reported status. 500

From the console I get the following information and warnings:

Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead map-of-science:618:0
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery-migrate-1.1.1.min.js:3:0
"Window Name: wiki.parliamentofthings.org" map-of-science:666:458
syntax error map-of-science.json:1:1
"pageHandler.get error" Object { readyState: 4, getResponseHeader: .ajax/N.getResponseHeader(), getAllResponseHeaders: .ajax/N.getAllResponseHeaders(), setRequestHeader: .ajax/N.setRequestHeader(), overrideMimeType: .ajax/N.overrideMimeType(), statusCode: .ajax/N.statusCode(), abort: .ajax/N.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 11 more… } 500 "error" "Internal Server Error" map-of-science:666:26625
".page keys " Array [ "154966d1" ] map-of-science:667:7521
"lineup keys" Array [ "154966d1" ] map-of-science:667:7660
"ajax error" Object { type: "ajaxError", timeStamp: 1428657373645, jQuery19106335917615261464: true, isTrigger: true, namespace: "", namespace_re: null, result: undefined, target: HTMLDocument → map-of-science, delegateTarget: HTMLDocument → map-of-science, currentTarget: HTMLDocument → map-of-science, 2 more… } Object { readyState: 4, getResponseHeader: .ajax/N.getResponseHeader(), getAllResponseHeaders: .ajax/N.getAllResponseHeaders(), setRequestHeader: .ajax/N.setRequestHeader(), overrideMimeType: .ajax/N.overrideMimeType(), statusCode: .ajax/N.statusCode(), abort: .ajax/N.abort(), state: .Deferred/r.state(), always: .Deferred/r.always(), then: .Deferred/r.then(), 11 more… } Object { url: "/map-of-science.json?random=9c116c9b", type: "GET", isLocal: false, global: true, processData: true, async: true, contentType: "application/x-www-form-urlencoded; charset=UTF-8", accepts: Object, contents: Object, responseFields: Object, 11 more… } map-of-science:666:13426
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. map-of-science:620:0
"textEditor" "900f81790a29ef8c" Object { append: true } map-of-science:666:5158
"textEditor" "900f81790a29ef8c" Object { append: true } map-of-science:666:5158

**Comment by opn** [comment]
OK - will do. I'd do it now - but first I need to learn more about how Node servers work and where they log stuff... it's not standard AFAIK - so where do I find the server logs for wiki-node?

**Comment by paul90** [comment]
How are you creating this page? *map-of-science* appears in `/system/slugs.json` but not in the sitemap, which would suggest that it is being created using something other than the normal page creation mechanism.

The contents of the response is `Server SyntaxError: Unexpected number`, I would suspect the contents of the page - probably not JSON?

**Comment by paul90** [comment]
Assuming you are using the install from `http://journal.hapgood.net/installing-on-digital-ocean.html` then the logs will be in `/var/log/upstart` look at wiki.log, or the compressed version if older logs are needed.

**Comment by WardCunningham** [comment]
David and I have been working on restoring some sites he lost working from scrapes I'd done for analysis. This involves scripts both he and I have written and is certainly not the normal path.

I see that the error page he got was trying to offer help but scrambled it by putting html tags in a non-html item. I'll fix this over the weekend.

**Comment by WardCunningham** [comment]
The error page formatting was an easy fix. Here is what it looks like now. (I see I have to find the css option for word wrapping with pre-formatted text.

![screen shot 2015-04-10 at 7 45 00 am](https://cloud.githubusercontent.com/assets/12127/7090121/9f67b212-df55-11e4-895d-df02041839b6.png)

**Comment by paul90** [comment]
Try
``` css
pre {
    word-wrap: break-word;
    overflow-wrap: break-word;
}
```

**Comment by WardCunningham** [comment]
Maybe that should be pre.error and go right after this?
https://github.com/fedwiki/wiki-client/blob/master/client/style.css#L1-L5

**Comment by paul90** [comment]
Yes, that should be good

**Comment by WardCunningham** [comment]
This looks better. And with long strings of noise in error messages maybe character wrap is better than word wrap. As I was editing style.css I was thinking that we really should think through some defaults for basic html tags that are consistent with our narrow pages.

![image](https://cloud.githubusercontent.com/assets/12127/7091812/b278ac56-df61-11e4-9e76-38976e287e90.png)

**Comment by opn** [comment]
Here are my server logs:
- https://gist.github.com/opn/af7765ad6407106a167f

**Comment by WardCunningham** [comment]
I see lots of messages in this log of the form:
```
GET /map-of-science.json?random=1f18782b 500 - - 24.300 ms
[ 'Res sent:', 500, [SyntaxError: Unexpected number] ]
```
I'm guessing that this is from the file map-of-science not being properly formatted json. I checked the file I sent you with jsonlint.com and it says it is ok. You should check the file that you are trying to serve the same way.

I suspect your script. I've offered to help you with that too but would rather do it off-list. Since this doesn't seem to be a fedwiki problem, and we have already fixed the formatting problem that surfaced with this issue, I'm going to go ahead and close this one.

![image](https://cloud.githubusercontent.com/assets/12127/7095367/a1860f66-df7e-11e4-8359-8b32fa160494.png)
