### ISSUE TITLE
Federated wiki on a laptop

### ISSUE THREAD

**Issue by coevolving** [fedwiki/wiki-node#51]
The "Hosting and Installation Guide" says " ... you will need to have a dedicated computer that is always connected to the internet" at https://github.com/WardCunningham/Smallest-Federated-Wiki/wiki/Hosting-and-Installation-Guide .

What is the impact if the computer is not always connected, (i) to the individual working on a disconnected laptop, and (ii) to the federation than can not rely on a persistent connection?

If a laptop running a federated wiki is disconnected from the Internet for 48 hours (e.g. travel time for an airplane ride plus ground transportation on both end), and edits are done on the disconnected laptop, will the federation "catch up" on changes?  Across the federation, if other forks start showing up, are there indicators that will (eventually) show up?

**Comment by paul90** [comment]
If you are running federated wiki on a laptop, when it is not connected to the network you will still be able to use it locally to work with any pages you have stored on it. But, as it is not accessible from elsewhere any attempts to connect to it will fail; (i) the sitemap will fail to load, the flag will stop at an angle and the flag will be blank, and (ii) your pages may be found elsewhere, if they have been forked to a site within the user's current neighbourhood.

Once the laptop is reconnected, the content will once again be visible within the federation - N.B. the client does not retry sitemaps that failed, your site will not become visible immediately. The user will need to reload the neighbourhood.

**Comment by almereyda** [comment]
Running wiki on a laptop was the initial root cause for https://github.com/WardCunningham/Smallest-Federated-Wiki/issues/410 .

I believe this can even be closed, as `wiki-client` will now happily fork as a proxy between two else unconnected wiki services.

**Comment by WardCunningham** [comment]
@coevolving If these answers are satisfactory then I will leave it to you to close this issue.

**Comment by coevolving** [comment]
I'll try installing federated wiki on a laptop.  It should be relatively straightforward, as I run Ubuntu.  Thanks for the directions.
